### ISSUE TITLE
Crashing issue with Preference Change listener

### ISSUE THREAD

**Issue by pablobaxter** [pablobaxter/Harmony#41]
There seems to be some sort of crashing issue when calling `toSet()` on the keys of the `WeakHashMap` used for the `OnSharedPrefernecesChangeListener`. Investigation underway.

**Comment by pablobaxter** [comment]
Example partial stacktrace:
```
Fatal Exception: java.util.NoSuchElementException
       at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:808)
       at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
       at kotlin.collections.CollectionsKt___CollectionsKt.toSet(_Collections.kt:1345)
       at com.frybits.harmony.HarmonyImpl$HarmonyEditor.commitToMemory(Harmony.kt:841)
       at com.frybits.harmony.HarmonyImpl$HarmonyEditor.apply(Harmony.kt:817)
```

**Comment by pablobaxter** [comment]
It appears as if I am not the first person to see this type crashing issue: https://issuetracker.google.com/issues/181683711

Like that ticket states, this does appear to be a rare crash, but for some reason is spiking with Android 11/12 as of late. In an app with tens of thousands of users, I'm seeing ~1k daily crashes. Harmony has not changed in this app, and previous releases of the app do not show this crash. It's possible that there could be something app side, but doing due diligence investigation to figure out why this spike is occurring.
