### ISSUE TITLE
Possible file I/O issue

### ISSUE THREAD

**Issue by sklinefelter** [pablobaxter/Harmony#52]
Hi @pablobaxter!

Seeing some indications of possible trouble reading/writing to the Harmony shared preferences on app start (although admittedly we're behind on the latest version - 1.1.11 instead of latest).

```
Caused by java.lang.IllegalStateException: Nesting problem: [EMPTY_DOCUMENT]
       at android.util.JsonWriter.beforeValue(JsonWriter.java:525)
       at android.util.JsonWriter.open(JsonWriter.java:239)
       at android.util.JsonWriter.beginObject(JsonWriter.java:222)
       at com.frybits.harmony.internal._InternalCoreHarmony__HarmonyJsonUtilsKt.putHarmony(_InternalCoreHarmony__HarmonyJsonUtils.kt:130)
       at com.frybits.harmony.internal._InternalCoreHarmony.putHarmony(_InternalCoreHarmony.java:1)
       at com.frybits.harmony.HarmonyImpl.initialLoad(HarmonyImpl.java:366)
       at com.frybits.harmony.HarmonyImpl.isLoadedTask$lambda-4(HarmonyImpl.java:173)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

This is occurring from our ContentProvider's `onCreate` when we first attempt to read one of the fields.  

Reporting in case you have some magic or know what could be going on here.

**Comment by pablobaxter** [comment]
Hey @sklinefelter ! Do you know if this occurs on a set of devices/OS or is this occurring on everything? Also, do you know how often this is occurring per user?

**Comment by sklinefelter** [comment]
@pablobaxter some additional details from the past 30 days (starting December ~22nd):

- 83% background (so not backgrounded all of the time)
- Android 8-14 reported (30% is the highest and on Android 11)
- _seems_ to be lower end devices, but I do see a Galaxy S21 5G which should have sufficient power.  Primarily Motorola (48%) and Samsung (30%) but Google, Xiaomi, and other manufacturers are non-zero
- Hard to say for certain # of times per user, but 5,295 crash events affecting 488 users

Anything else that would be helpful?
